# This file contains helper functions to format YAML output from yaml_generator.py.
"""
Custom YAML formatting to ensure the generated docker-compose YAML is clean and human-readable.

Addresses PyYAML's deafult formatting quirks:
  - Strings that look like numbers/booleans get quoted properly
  - Multiline strings use block style (|) instead of escape sequences
  - Lists of scalars stay compact (flow style on short lists)
  - Top-level sections are separated by a blank line for readability
"""

import yaml
from typing import Any

# Custom Dumper 

class ComposeYAMLDumper(yaml.Dumper):
    """
    Extends yaml.Dumper with Docker Compose-friendly formatting rules:
      - Indents list items by 2 spaces (no extra offset)
      - Preserves insertion order (dicts stay in the order we build them)
      - Quotes strings that PyYAML would otherwise misrepresent
    """

    def increase_indent(self, flow=False, indentless=False):
        # Keep list items flush with their parent key (standard compose style)
        return super().increase_indent(flow=flow, indentless=False)


# Custom Representers: Teach dumper how to render specific Python types in a Docker Compose-friendly way

def _represent_str(dumper: ComposeYAMLDumper, data: str) -> yaml.Node:
    """
    Use literal block style (|) for multiline strings so they remain readable.
    Otherwise fall back to the default plain/quoted scalar.
    """
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


def _represent_dict(dumper: ComposeYAMLDumper, data: dict) -> yaml.Node:
    """
    Render dicts as block mappings, preserving insertion order.
    (PyYAML sorts keys by default — we override that here.)
    """
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


def _represent_none(dumper: ComposeYAMLDumper, _: None) -> yaml.Node:
    """
    Render None as an empty value ('') instead of 'null',
    which is the conventional style in docker-compose files.
    e.g.  volumes:\n  postgres_data:   (not  postgres_data: null)
    """
    return dumper.represent_scalar("tag:yaml.org,2002:null", "")

# Register the custom representers on the dumper
ComposeYAMLDumper.add_representer(str, _represent_str)
ComposeYAMLDumper.add_representer(dict, _represent_dict)
ComposeYAMLDumper.add_representer(type(None), _represent_none)


# Public function to generate YAML using the custom dumper

def dump_compose(compose_dict: dict) -> str:
    """
    Serialize a compose dictionary to a clean, human-readable YAML string.

    Post-processing steps applied after yaml.dump:
      1. A blank line is inserted before each top-level section key
         (version / services / networks / volumes) so the file is easy to scan.
      2. A header comment is prepended explaining the file was auto-generated.

    Args:
        compose_dict: The fully-built compose structure (version, services, …)

    Returns:
        A formatted YAML string ready to be written to docker-compose.yml
    """
    raw = yaml.dump(
        compose_dict,
        Dumper=ComposeYAMLDumper,
        default_flow_style=False,
        sort_keys=False,       # preserve our insertion order
        indent=2,
        allow_unicode=True,
        width=120,             # avoid aggressive line-wrapping on long env vars
    )

    formatted = _insert_section_breaks(raw)
    return _prepend_header(formatted)

# Private formatting helpers

_TOP_LEVEL_KEYS = {"services:", "networks:", "volumes:"}


def _insert_section_breaks(yaml_str: str) -> str:
    """
    Insert a blank line before each top-level section (services, networks, volumes)
    so the generated file looks like a hand-crafted compose file.

    Before:
        version: '3.8'
        services:
          ...
        networks:

    After:
        version: '3.8'

        services:
          ...

        networks:
    """
    lines = yaml_str.splitlines()
    output = []

    for line in lines:
        # Only match top-level keys (no leading whitespace) to avoid
        # adding blank lines before indented 'volumes:' inside a service block
        is_top_level = not line.startswith(" ") and not line.startswith("\t")
        if is_top_level and any(line.startswith(key) for key in _TOP_LEVEL_KEYS):
            # Only add blank line if the previous line wasn't already blank
            if output and output[-1] != "":
                output.append("")
        output.append(line)

    return "\n".join(output) + "\n"


def _prepend_header(yaml_str: str) -> str:
    """
    Prepend a comment header to the YAML output so it's clear the file
    was generated by ContainerCraft and shouldn't be hand-edited blindly.
    """
    header = (
        "# Generated by ContainerCraft\n"
        "# Do not edit manually — re-export from the visual editor instead.\n"
        "\n"
    )
    return header + yaml_str